# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2f56ebe5efdde5e8c2f627c5ac4c4388683d445e42d37b5cfabb96255ec1c0387634a210f54e1891632b4a2d8e4a0fd5aaaf37a5f71cdb684909e975724ecfc

test:
  secret_key_base: e73be6bac4f5106e4270760fff4b3d51ba3ef29406c6abd8c13e9f26b1077461a221b58237a506ce96ef85c872e8fe4feb9d059ae7ea4d695aa4d25d13ee451b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
